version: 2
updates:
- package-ecosystem: "npm"
  directory: "/example"
  schedule:
    interval: "daily"
  groups:
    remix:
      patterns:
      - "@remix-run*"
      - "remix"
    react:
      patterns:
      - "react*"
- package-ecosystem: "npm"
  directory: "/packages/remix-alb-adapter"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
