version: 3

includes:
  adapter:
    taskfile: packages/remix-alb-adapter/
    dir: packages/remix-alb-adapter/

tasks:
  default:
    cmds:
    - task: adapter:default

  install:
    cmds:
    - npm ci
