version: 3

tasks:
  default:
    cmds:
    - task: lint
    - task: prettier
    - task: test
    - task: build

  publish:
    deps: [ default ]
    cmds:
    - npm publish

  lint:
    cmds: [ npm run lint ]
  prettier:
    cmds: [ npm run prettier ]
  test:
    cmds:
    - npm run test
  build:
    cmds:
    - npm run build


